use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .to_path_buf()
}

struct Fixture {
    root: PathBuf,
}

impl Fixture {
    fn new(name: &str) -> Self {
        let root = std::env::temp_dir().join(format!(
            "runa-release-check-{name}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("system time should be after unix epoch")
                .as_nanos()
        ));
        fs::create_dir_all(&root).expect("fixture root should be created");
        Self { root }
    }

    fn write(&self, relative: &str, contents: &str) {
        let path = self.root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("fixture parent should be created");
        }
        fs::write(path, contents).expect("fixture file should be written");
    }

    fn install_release_check(&self) {
        let source = workspace_root().join("scripts/release-check");
        let destination = self.root.join("scripts/release-check");
        fs::create_dir_all(destination.parent().expect("script parent"))
            .expect("script parent should be created");
        fs::copy(source, &destination).expect("release-check script should exist");
        fs::set_permissions(&destination, fs::Permissions::from_mode(0o755))
            .expect("release-check script should be executable");
    }

    fn run_release_check(&self, args: &[&str]) -> Output {
        Command::new("bash")
            .arg(self.root.join("scripts/release-check"))
            .args(args)
            .current_dir(&self.root)
            .output()
            .expect("release-check should run")
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

fn workspace_manifest(version: &str, members: &[&str]) -> String {
    let members = members
        .iter()
        .map(|member| format!("    \"{member}\","))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"[workspace]
members = [
{members}
]

[workspace.package]
version = "{version}"
edition = "2024"
license = "MIT"
"#
    )
}

fn cargo_lock_with_packages(packages: &[(&str, &str)]) -> String {
    let packages = packages
        .iter()
        .map(|(name, version)| {
            format!(
                r#"[[package]]
name = "{name}"
version = "{version}"
"#
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"# This file is automatically @generated by Cargo.
version = 4

{packages}
"#
    )
}

fn valid_fixture(name: &str, version: &str) -> Fixture {
    let fixture = Fixture::new(name);
    fixture.write(
        "Cargo.toml",
        &workspace_manifest(version, &["runa-cli", "libagent", "runa-mcp"]),
    );
    fixture.write(
        "Cargo.lock",
        &cargo_lock_with_packages(&[
            ("runa-cli", version),
            ("libagent", version),
            ("runa-mcp", version),
        ]),
    );
    fixture.write(
        "runa-cli/Cargo.toml",
        r#"[package]
name = "runa-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
"#,
    );
    fixture.write("runa-cli/src/main.rs", "fn main() {}\n");
    fixture.write(
        "libagent/Cargo.toml",
        r#"[package]
name = "libagent"
version.workspace = true
edition.workspace = true
license.workspace = true
"#,
    );
    fixture.write("libagent/src/lib.rs", "");
    fixture.write(
        "runa-mcp/Cargo.toml",
        r#"[package]
name = "runa-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true
"#,
    );
    fixture.write("runa-mcp/src/main.rs", "fn main() {}\n");
    fixture.write(
        "CHANGELOG.md",
        &format!(
            r#"# Changelog

## [Unreleased]

## [{version}] — 2026-05-09

### Added

- Release ceremony tooling.
"#
        ),
    );
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore annotated tag refs
        run: git fetch --tags --force origin

      - name: Verify restored tag matches event
        run: |
          restored_commit=$(git rev-parse "refs/tags/$GITHUB_REF_NAME^{commit}")
          if [ "$restored_commit" != "$GITHUB_SHA" ]; then
            echo "Tag $GITHUB_REF_NAME moved since trigger: expected $GITHUB_SHA, got $restored_commit" >&2
            exit 1
          fi

      - name: Require annotated tag
        run: test "$(git cat-file -t "refs/tags/$GITHUB_REF_NAME")" = tag

      - name: Require tag target on main
        run: git merge-base --is-ancestor "$tag_commit" refs/remotes/origin/main

      - name: Validate release tag
        run: ./scripts/release-check release "$GITHUB_REF_NAME"

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
"#,
    );
    fixture.install_release_check();
    fixture
}

fn assert_success(output: &Output) {
    assert!(
        output.status.success(),
        "command failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn assert_failure_contains(output: &Output, expected: &str) {
    assert!(
        !output.status.success(),
        "command unexpectedly succeeded\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(expected),
        "stderr did not contain {expected:?}\nstderr:\n{stderr}"
    );
}

#[test]
fn metadata_accepts_a_coherent_runa_release_surface() {
    let fixture = valid_fixture("metadata-success", "1.2.3");

    let output = fixture.run_release_check(&["metadata"]);

    assert_success(&output);
}

#[test]
fn metadata_rejects_release_workflows_without_v_star_tag_delegation() {
    let fixture = valid_fixture("metadata-workflow-old-tag-filters", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        ".github/workflows/release.yml must declare exactly one release tag pattern",
    );
}

#[test]
fn metadata_rejects_release_workflows_with_path_filters_on_tag_publication() {
    let fixture = valid_fixture("metadata-workflow-path-filter", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"
    paths:
      - "CHANGELOG.md"
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        ".github/workflows/release.yml tag publication must not use paths filters",
    );
}

#[test]
fn metadata_rejects_release_workflows_without_early_tag_validation() {
    let fixture = valid_fixture("metadata-workflow-missing-validation", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        ".github/workflows/release.yml must validate the release tag before expensive release work",
    );
}

#[test]
fn metadata_rejects_release_workflows_that_validate_tags_before_tag_trust() {
    let fixture = valid_fixture("metadata-workflow-pretrust-validation", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate release tag
        run: ./scripts/release-check release "$GITHUB_REF_NAME"

      - name: Restore annotated tag refs
        run: git fetch --tags --force origin

      - name: Verify restored tag matches event
        run: |
          restored_commit=$(git rev-parse "refs/tags/$GITHUB_REF_NAME^{commit}")
          if [ "$restored_commit" != "$GITHUB_SHA" ]; then
            echo "Tag $GITHUB_REF_NAME moved since trigger: expected $GITHUB_SHA, got $restored_commit" >&2
            exit 1
          fi

      - name: Require annotated tag
        run: test "$(git cat-file -t "refs/tags/$GITHUB_REF_NAME")" = tag

      - name: Require tag target on main
        run: git merge-base --is-ancestor "$tag_commit" refs/remotes/origin/main

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        ".github/workflows/release.yml must establish tag trust before running repository code",
    );
}

#[test]
fn metadata_rejects_release_workflows_that_do_not_restore_annotated_tag_refs() {
    let fixture = valid_fixture("metadata-workflow-missing-tag-ref-restore", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify restored tag matches event
        run: |
          restored_commit=$(git rev-parse "refs/tags/$GITHUB_REF_NAME^{commit}")
          if [ "$restored_commit" != "$GITHUB_SHA" ]; then
            echo "Tag $GITHUB_REF_NAME moved since trigger: expected $GITHUB_SHA, got $restored_commit" >&2
            exit 1
          fi

      - name: Require annotated tag
        run: test "$(git cat-file -t "refs/tags/$GITHUB_REF_NAME")" = tag

      - name: Require tag target on main
        run: git merge-base --is-ancestor "$tag_commit" refs/remotes/origin/main

      - name: Validate release tag
        run: ./scripts/release-check release "$GITHUB_REF_NAME"

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        ".github/workflows/release.yml must restore annotated tag refs before checking tag type",
    );
}

#[test]
fn metadata_rejects_release_workflows_that_do_not_verify_restored_tag_matches_event() {
    let fixture = valid_fixture("metadata-workflow-missing-event-identity", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore annotated tag refs
        run: git fetch --tags --force origin

      - name: Require annotated tag
        run: test "$(git cat-file -t "refs/tags/$GITHUB_REF_NAME")" = tag

      - name: Require tag target on main
        run: git merge-base --is-ancestor "$tag_commit" refs/remotes/origin/main

      - name: Validate release tag
        run: ./scripts/release-check release "$GITHUB_REF_NAME"

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        ".github/workflows/release.yml must verify the restored tag matches the triggering event before checking tag type",
    );
}

#[test]
fn metadata_ignores_yaml_and_shell_comments_when_validating_workflow_shape() {
    let fixture = valid_fixture("metadata-workflow-comment-only", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # run: ./scripts/release-check release "$GITHUB_REF_NAME"
      - name: Restore annotated tag refs
        run: git fetch --tags --force origin

      - name: Verify restored tag matches event
        run: |
          restored_commit=$(git rev-parse "refs/tags/$GITHUB_REF_NAME^{commit}")
          if [ "$restored_commit" != "$GITHUB_SHA" ]; then
            echo "Tag $GITHUB_REF_NAME moved since trigger: expected $GITHUB_SHA, got $restored_commit" >&2
            exit 1
          fi

      - name: Commented annotated tag check
        run: |
          # git cat-file -t "refs/tags/$GITHUB_REF_NAME"

      - name: Require tag target on main
        run: git merge-base --is-ancestor "$tag_commit" refs/remotes/origin/main

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        ".github/workflows/release.yml must validate the release tag before expensive release work",
    );
}

#[test]
fn metadata_rejects_a_missing_workspace_version() {
    let fixture = valid_fixture("metadata-missing-version", "1.2.3");
    fixture.write(
        "Cargo.toml",
        r#"[workspace]
members = ["runa-cli"]

[workspace.package]
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(&output, "workspace package version not found");
}

#[test]
fn metadata_rejects_workspace_package_versions_drifted_in_cargo_lock() {
    let fixture = valid_fixture("metadata-lock-version-drift", "1.2.3");
    fixture.write(
        "Cargo.lock",
        &cargo_lock_with_packages(&[
            ("runa-cli", "1.2.3"),
            ("libagent", "1.2.4"),
            ("runa-mcp", "1.2.3"),
        ]),
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        "Cargo.lock package libagent version 1.2.4 does not match workspace version 1.2.3",
    );
}

#[test]
fn metadata_rejects_new_workspace_members_that_do_not_inherit_the_workspace_version() {
    let fixture = valid_fixture("metadata-extra-member-version-inherit", "1.2.3");
    fixture.write(
        "Cargo.toml",
        &workspace_manifest("1.2.3", &["runa-cli", "libagent", "runa-mcp", "extra"]),
    );
    fixture.write(
        "extra/Cargo.toml",
        r#"[package]
name = "extra"
version = "1.2.3"
edition.workspace = true
license.workspace = true
"#,
    );
    fixture.write("extra/src/lib.rs", "");

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        "extra/Cargo.toml must inherit version.workspace = true",
    );
}

#[test]
fn metadata_extracts_workspace_versions_with_comments_and_whitespace() {
    let fixture = valid_fixture("metadata-version-formatting", "1.2.3");
    fixture.write(
        "Cargo.toml",
        r#"[workspace]
members = [
    "runa-cli",
    "libagent",
    "runa-mcp",
]

[workspace.package] # shared package substrate
  version   =   "1.2.3" # release identity
edition = "2024"
license = "MIT"
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_success(&output);
}

#[test]
fn metadata_rejects_malformed_changelog_release_headings() {
    let fixture = valid_fixture("metadata-malformed-changelog", "1.2.3");
    fixture.write(
        "CHANGELOG.md",
        r#"# Changelog

## [Unreleased]

## [1.2.3] - 2026-05-09
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(&output, "release heading is malformed");
}

#[test]
fn metadata_rejects_unsupported_workspace_prerelease_versions() {
    let fixture = valid_fixture("metadata-unsupported-workspace-prerelease", "1.2.3-beta.1");

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        "workspace version must look like X.Y.Z or X.Y.Z-rc.N: 1.2.3-beta.1",
    );
}

#[test]
fn metadata_rejects_leading_zero_workspace_versions() {
    let fixture = valid_fixture("metadata-leading-zero", "01.2.3");

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        "workspace version must look like X.Y.Z or X.Y.Z-rc.N: 01.2.3",
    );
}

#[test]
fn notes_emit_the_matching_changelog_section_without_outer_blank_lines() {
    let fixture = valid_fixture("notes-success", "1.2.3");

    let output = fixture.run_release_check(&["notes", "v1.2.3"]);

    assert_success(&output);
    assert_eq!(
        String::from_utf8(output.stdout).expect("stdout should be utf-8"),
        "### Added\n\n- Release ceremony tooling.\n"
    );
}

#[test]
fn notes_accept_release_candidate_tags_without_suffix_duplication() {
    let fixture = valid_fixture("notes-rc-success", "1.2.3-rc.2");

    let output = fixture.run_release_check(&["notes", "v1.2.3-rc.2"]);

    assert_success(&output);
    assert_eq!(
        String::from_utf8(output.stdout).expect("stdout should be utf-8"),
        "### Added\n\n- Release ceremony tooling.\n"
    );
}

#[test]
fn notes_rejects_unsupported_beta_tags() {
    let fixture = valid_fixture("notes-beta-tag", "1.2.3-beta.1");

    let output = fixture.run_release_check(&["notes", "v1.2.3-beta.1"]);

    assert_failure_contains(
        &output,
        "release version must look like vX.Y.Z or vX.Y.Z-rc.N: v1.2.3-beta.1",
    );
}

#[test]
fn notes_rejects_leading_zero_stable_tags() {
    let fixture = valid_fixture("notes-leading-zero-stable-tag", "1.2.3");

    let output = fixture.run_release_check(&["notes", "v01.2.3"]);

    assert_failure_contains(
        &output,
        "release version must look like vX.Y.Z or vX.Y.Z-rc.N: v01.2.3",
    );
}

#[test]
fn notes_rejects_leading_zero_release_candidate_numbers() {
    let fixture = valid_fixture("notes-leading-zero-rc-tag", "1.2.3-rc.1");

    let output = fixture.run_release_check(&["notes", "v1.2.3-rc.01"]);

    assert_failure_contains(
        &output,
        "release version must look like vX.Y.Z or vX.Y.Z-rc.N: v1.2.3-rc.01",
    );
}

#[test]
fn notes_rejects_release_candidate_zero() {
    let fixture = valid_fixture("notes-rc-zero-tag", "1.2.3-rc.1");

    let output = fixture.run_release_check(&["notes", "v1.2.3-rc.0"]);

    assert_failure_contains(
        &output,
        "release version must look like vX.Y.Z or vX.Y.Z-rc.N: v1.2.3-rc.0",
    );
}

#[test]
fn release_rejects_tag_versions_that_do_not_match_workspace_version() {
    let fixture = valid_fixture("release-version-mismatch", "1.2.3");

    let output = fixture.run_release_check(&["release", "v1.2.4"]);

    assert_failure_contains(
        &output,
        "workspace version 1.2.3 does not match tag version 1.2.4",
    );
}

#[test]
fn release_accepts_source_only_validation_before_binaries_are_built() {
    let fixture = valid_fixture("release-source-only", "1.2.3");

    let output = fixture.run_release_check(&["release", "v1.2.3"]);

    assert_success(&output);
}

#[test]
fn release_rejects_partial_binary_validation_arguments() {
    let fixture = valid_fixture("release-partial-binary-args", "1.2.3");
    fixture.write("fake-runa", "#!/usr/bin/env sh\nprintf 'runa 1.2.3\\n'\n");
    fs::set_permissions(
        fixture.root.join("fake-runa"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runa should be executable");

    let output = fixture.run_release_check(&["release", "v1.2.3", "--runa-bin", "fake-runa"]);

    assert_failure_contains(
        &output,
        "--runa-bin and --runa-mcp-bin must be supplied together",
    );
}

#[test]
fn release_rejects_empty_binary_validation_paths() {
    let fixture = valid_fixture("release-empty-binary-args", "1.2.3");

    let output =
        fixture.run_release_check(&["release", "v1.2.3", "--runa-bin", "", "--runa-mcp-bin", ""]);

    assert_failure_contains(&output, "--runa-bin requires a non-empty path");
}

#[test]
fn release_rejects_empty_runa_binary_path_even_with_runa_mcp_path() {
    let fixture = valid_fixture("release-empty-runa-bin", "1.2.3");
    fixture.write(
        "fake-runa-mcp",
        "#!/usr/bin/env sh\nprintf 'runa-mcp 1.2.3\\n'\n",
    );
    fs::set_permissions(
        fixture.root.join("fake-runa-mcp"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runa-mcp should be executable");

    let output = fixture.run_release_check(&[
        "release",
        "v1.2.3",
        "--runa-bin",
        "",
        "--runa-mcp-bin",
        "fake-runa-mcp",
    ]);

    assert_failure_contains(&output, "--runa-bin requires a non-empty path");
}

#[test]
fn release_rejects_empty_runa_mcp_binary_path_even_with_runa_path() {
    let fixture = valid_fixture("release-empty-runa-mcp-bin", "1.2.3");
    fixture.write("fake-runa", "#!/usr/bin/env sh\nprintf 'runa 1.2.3\\n'\n");
    fs::set_permissions(
        fixture.root.join("fake-runa"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runa should be executable");

    let output = fixture.run_release_check(&[
        "release",
        "v1.2.3",
        "--runa-bin",
        "fake-runa",
        "--runa-mcp-bin",
        "",
    ]);

    assert_failure_contains(&output, "--runa-mcp-bin requires a non-empty path");
}

#[test]
fn release_checks_both_runa_binary_identities() {
    let fixture = valid_fixture("release-binaries-success", "1.2.3");
    fixture.write("fake-runa", "#!/usr/bin/env sh\nprintf 'runa 1.2.3\\n'\n");
    fixture.write(
        "fake-runa-mcp",
        "#!/usr/bin/env sh\nprintf 'runa-mcp 1.2.3\\n'\n",
    );
    fs::set_permissions(
        fixture.root.join("fake-runa"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runa should be executable");
    fs::set_permissions(
        fixture.root.join("fake-runa-mcp"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runa-mcp should be executable");

    let output = fixture.run_release_check(&[
        "release",
        "v1.2.3",
        "--runa-bin",
        "fake-runa",
        "--runa-mcp-bin",
        "fake-runa-mcp",
    ]);

    assert_success(&output);
}

#[test]
fn release_rejects_runa_mcp_binary_version_mismatches() {
    let fixture = valid_fixture("release-runa-mcp-mismatch", "1.2.3");
    fixture.write("fake-runa", "#!/usr/bin/env sh\nprintf 'runa 1.2.3\\n'\n");
    fixture.write(
        "fake-runa-mcp",
        "#!/usr/bin/env sh\nprintf 'runa-mcp 9.9.9\\n'\n",
    );
    fs::set_permissions(
        fixture.root.join("fake-runa"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runa should be executable");
    fs::set_permissions(
        fixture.root.join("fake-runa-mcp"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runa-mcp should be executable");

    let output = fixture.run_release_check(&[
        "release",
        "v1.2.3",
        "--runa-bin",
        "fake-runa",
        "--runa-mcp-bin",
        "fake-runa-mcp",
    ]);

    assert_failure_contains(&output, "runa-mcp binary reports");
}

#[test]
fn release_rejects_changelog_headings_that_only_regex_match_the_tag_version() {
    let fixture = valid_fixture("release-regex-matched-heading", "1.2.3-rc.2");
    fixture.write(
        "CHANGELOG.md",
        r#"# Changelog

## [Unreleased]

## [1.2.3-rcZ2] — 2026-05-09

### Added

- Release ceremony tooling.
"#,
    );

    let output = fixture.run_release_check(&["release", "v1.2.3-rc.2"]);

    assert_failure_contains(&output, "release heading");
}

#[test]
fn release_check_surface_stays_bounded_to_runa_owned_artifacts() {
    let fixture = valid_fixture("release-no-container-surface", "1.2.3");

    let output = fixture.run_release_check(&["release", "v1.2.3", "--base-image", "base:v1.2.3"]);

    assert_failure_contains(&output, "unknown release option: --base-image");
}
