allow-branch = ["main"]
release = true
shared-version = true
dependent-version = "fix"
consolidate-commits = true
pre-release-replacements = []
pre-release-hook = ["/usr/bin/true"]
pre-release-commit-message = "chore(release): bump workspace version to {{version}}"
tag = true
tag-name = "v{{version}}"
tag-message = "Release {{tag_name}}"
sign-commit = false
sign-tag = false
push = true
push-remote = "origin"
push-options = []
publish = false
owners = []
verify = true
enable-features = []
enable-all-features = false
metadata = "optional"
certs-source = "webpki"
